version: '3'

services:
  postgresql:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: preonboarding_db
      TZ: 'Asia/Seoul'
    volumes:
      - ./volumes/db_data2:/var/lib/postgresql/data

  express:
    container_name: express_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: 'postgresql://user:user1234@postgresql:5432/preonboarding_db?schema=public'
      PORT: 5000
    depends_on:
      - postgresql
