version: '3'

services:
  postgresql:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: preonboarding_db
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready']
    #   interval: 1s
    #   timeout: 5s
    #   retries: 10
